[package]
name = "sofar"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"

[dev-dependencies]
assert_approx_eq = "1.1.0"
rsofa = "0.5.0"

[lints.clippy]
excessive_precision = "allow"
